export type Feed = {
  feedId: string;
  feedName: string;
  feedDescription: string;
  feedType: string;
  businessDomain: string;
  dataOwner: string;
  productOwner: string;
  dataSource: "CoAction" | "Third Party";
  sourceSystem: string;
  vendorPartner: string;
  transferMethod: "SFTP" | "API" | "Other";
  fileFormat: string;
  encryption: string;
  containsPII: "Yes" | "No";
  masking: "Yes" | "No";
  provisionedToGP: "Yes" | "No";
  dateProvisioned: string;
  jira: string;
  credentials: string;
  accessOwners: string;
  accessType: string;
  lastChangeDate: string;
  version: string;
  comments: string;
};

export const mockFeeds: Feed[] = [
  {
    feedId: "FD-1001",
    feedName: "Policy Master Daily",
    feedDescription: "Daily extract of policy master records for downstream analytics.",
    feedType: "Batch",
    businessDomain: "Underwriting",
    dataOwner: "J. Stevens",
    productOwner: "M. Patel",
    dataSource: "CoAction",
    sourceSystem: "Guidewire PC",
    vendorPartner: "Internal",
    transferMethod: "SFTP",
    fileFormat: "CSV",
    encryption: "PGP",
    containsPII: "Yes",
    masking: "Yes",
    provisionedToGP: "Yes",
    dateProvisioned: "2025-08-12",
    jira: "DATA-2351",
    credentials: "Vault: feed/policy-master",
    accessOwners: "Data Platform Team",
    accessType: "Service Account",
    lastChangeDate: "2026-04-20",
    version: "1.4.0",
    comments: "Schema updated for new auto coverage fields.",
  },
  {
    feedId: "FD-1002",
    feedName: "Claims Loss Run",
    feedDescription: "Monthly loss run feed shared with reinsurance partners.",
    feedType: "Batch",
    businessDomain: "Claims",
    dataOwner: "R. Khan",
    productOwner: "L. Nguyen",
    dataSource: "CoAction",
    sourceSystem: "Guidewire CC",
    vendorPartner: "Munich Re",
    transferMethod: "SFTP",
    fileFormat: "XLSX",
    encryption: "TLS",
    containsPII: "No",
    masking: "No",
    provisionedToGP: "Yes",
    dateProvisioned: "2025-09-01",
    jira: "DATA-2402",
    credentials: "Vault: feed/loss-run",
    accessOwners: "Reinsurance Ops",
    accessType: "SFTP Key",
    lastChangeDate: "2026-03-28",
    version: "2.1.1",
    comments: "Added cause-of-loss code mapping.",
  },
  {
    feedId: "FD-1003",
    feedName: "Bureau Submission - ISO",
    feedDescription: "Quarterly statistical submission to ISO bureau.",
    feedType: "Bureau",
    businessDomain: "Compliance",
    dataOwner: "S. Carter",
    productOwner: "S. Carter",
    dataSource: "Third Party",
    sourceSystem: "Stat Reporting Engine",
    vendorPartner: "Verisk ISO",
    transferMethod: "API",
    fileFormat: "JSON",
    encryption: "TLS",
    containsPII: "No",
    masking: "No",
    provisionedToGP: "No",
    dateProvisioned: "—",
    jira: "DATA-2199",
    credentials: "Vault: feed/iso-api",
    accessOwners: "Compliance Reporting",
    accessType: "OAuth2",
    lastChangeDate: "2026-04-10",
    version: "3.0.0",
    comments: "Switched from SFTP to API delivery.",
  },
  {
    feedId: "FD-1004",
    feedName: "Producer Commission Statements",
    feedDescription: "Monthly commission statements distributed to producers.",
    feedType: "Batch",
    businessDomain: "Distribution",
    dataOwner: "T. Alvarez",
    productOwner: "M. Patel",
    dataSource: "CoAction",
    sourceSystem: "Commission Hub",
    vendorPartner: "Internal",
    transferMethod: "SFTP",
    fileFormat: "PDF",
    encryption: "PGP",
    containsPII: "Yes",
    masking: "No",
    provisionedToGP: "No",
    dateProvisioned: "—",
    jira: "DATA-2510",
    credentials: "Vault: feed/commissions",
    accessOwners: "Producer Ops",
    accessType: "SFTP Key",
    lastChangeDate: "2026-04-22",
    version: "1.2.3",
    comments: "Producer onboarding fields added.",
  },
  {
    feedId: "FD-1005",
    feedName: "Third-Party Telematics",
    feedDescription: "Streaming telematics data from partner devices.",
    feedType: "Streaming",
    businessDomain: "Auto",
    dataOwner: "P. Chen",
    productOwner: "L. Nguyen",
    dataSource: "Third Party",
    sourceSystem: "Cambridge Mobile",
    vendorPartner: "CMT",
    transferMethod: "API",
    fileFormat: "JSON",
    encryption: "TLS",
    containsPII: "Yes",
    masking: "Yes",
    provisionedToGP: "Yes",
    dateProvisioned: "2025-11-15",
    jira: "DATA-2620",
    credentials: "Vault: feed/cmt",
    accessOwners: "Auto Analytics",
    accessType: "OAuth2",
    lastChangeDate: "2026-04-30",
    version: "4.0.1",
    comments: "PII masking applied to driver IDs.",
  },
  {
    feedId: "FD-1006",
    feedName: "MGA Bordereau",
    feedDescription: "Weekly bordereau from managing general agents.",
    feedType: "Batch",
    businessDomain: "Underwriting",
    dataOwner: "J. Stevens",
    productOwner: "M. Patel",
    dataSource: "Third Party",
    sourceSystem: "MGA Portal",
    vendorPartner: "Atlas MGA",
    transferMethod: "SFTP",
    fileFormat: "CSV",
    encryption: "PGP",
    containsPII: "Yes",
    masking: "Yes",
    provisionedToGP: "Yes",
    dateProvisioned: "2025-07-22",
    jira: "DATA-2055",
    credentials: "Vault: feed/atlas-mga",
    accessOwners: "MGA Operations",
    accessType: "SFTP Key",
    lastChangeDate: "2026-02-18",
    version: "2.4.0",
    comments: "Added written premium reconciliation.",
  },
  {
    feedId: "FD-1007",
    feedName: "Billing Receivables",
    feedDescription: "Daily AR snapshot for finance reporting.",
    feedType: "Batch",
    businessDomain: "Finance",
    dataOwner: "K. Brooks",
    productOwner: "K. Brooks",
    dataSource: "CoAction",
    sourceSystem: "Guidewire BC",
    vendorPartner: "Internal",
    transferMethod: "SFTP",
    fileFormat: "CSV",
    encryption: "PGP",
    containsPII: "No",
    masking: "No",
    provisionedToGP: "Yes",
    dateProvisioned: "2025-06-30",
    jira: "DATA-1980",
    credentials: "Vault: feed/billing-ar",
    accessOwners: "Finance BI",
    accessType: "Service Account",
    lastChangeDate: "2026-04-05",
    version: "1.7.2",
    comments: "—",
  },
  {
    feedId: "FD-1008",
    feedName: "Fraud Watchlist",
    feedDescription: "External fraud watchlist consumed via API.",
    feedType: "API",
    businessDomain: "Claims",
    dataOwner: "R. Khan",
    productOwner: "L. Nguyen",
    dataSource: "Third Party",
    sourceSystem: "LexisNexis",
    vendorPartner: "LexisNexis",
    transferMethod: "API",
    fileFormat: "JSON",
    encryption: "TLS",
    containsPII: "Yes",
    masking: "No",
    provisionedToGP: "No",
    dateProvisioned: "—",
    jira: "DATA-2701",
    credentials: "Vault: feed/lexis-api",
    accessOwners: "SIU Team",
    accessType: "API Key",
    lastChangeDate: "2026-04-29",
    version: "1.0.5",
    comments: "Throttled to 500 req/min.",
  },
  {
    feedId: "FD-1009",
    feedName: "Reinsurance Cessions",
    feedDescription: "Monthly cessions feed to reinsurance partners.",
    feedType: "Batch",
    businessDomain: "Reinsurance",
    dataOwner: "S. Carter",
    productOwner: "M. Patel",
    dataSource: "CoAction",
    sourceSystem: "Reinsurance Hub",
    vendorPartner: "Swiss Re",
    transferMethod: "SFTP",
    fileFormat: "CSV",
    encryption: "PGP",
    containsPII: "No",
    masking: "No",
    provisionedToGP: "Yes",
    dateProvisioned: "2025-10-05",
    jira: "DATA-2455",
    credentials: "Vault: feed/cessions",
    accessOwners: "Reinsurance Ops",
    accessType: "SFTP Key",
    lastChangeDate: "2026-03-12",
    version: "2.0.0",
    comments: "Treaty year 2026 layout active.",
  },
  {
    feedId: "FD-1010",
    feedName: "HR Roster",
    feedDescription: "Weekly employee roster for entitlements.",
    feedType: "Batch",
    businessDomain: "HR",
    dataOwner: "A. Donnelly",
    productOwner: "A. Donnelly",
    dataSource: "Third Party",
    sourceSystem: "Workday",
    vendorPartner: "Workday",
    transferMethod: "SFTP",
    fileFormat: "CSV",
    encryption: "PGP",
    containsPII: "Yes",
    masking: "Yes",
    provisionedToGP: "No",
    dateProvisioned: "—",
    jira: "DATA-2588",
    credentials: "Vault: feed/workday",
    accessOwners: "IAM Team",
    accessType: "SFTP Key",
    lastChangeDate: "2026-04-18",
    version: "1.1.0",
    comments: "—",
  },
  {
    feedId: "FD-1011",
    feedName: "Catastrophe Modeling Output",
    feedDescription: "Quarterly cat model results from vendor.",
    feedType: "Batch",
    businessDomain: "Actuarial",
    dataOwner: "P. Chen",
    productOwner: "M. Patel",
    dataSource: "Third Party",
    sourceSystem: "RMS",
    vendorPartner: "Moody's RMS",
    transferMethod: "Other",
    fileFormat: "Parquet",
    encryption: "TLS",
    containsPII: "No",
    masking: "No",
    provisionedToGP: "Yes",
    dateProvisioned: "2025-12-01",
    jira: "DATA-2810",
    credentials: "Vault: feed/rms",
    accessOwners: "Actuarial Modeling",
    accessType: "Service Account",
    lastChangeDate: "2026-04-01",
    version: "5.2.0",
    comments: "Hurricane season refresh complete.",
  },
  {
    feedId: "FD-1012",
    feedName: "Customer Communications Log",
    feedDescription: "Outbound communications log for compliance.",
    feedType: "Batch",
    businessDomain: "Compliance",
    dataOwner: "S. Carter",
    productOwner: "S. Carter",
    dataSource: "CoAction",
    sourceSystem: "Comms Platform",
    vendorPartner: "Internal",
    transferMethod: "SFTP",
    fileFormat: "JSON",
    encryption: "PGP",
    containsPII: "Yes",
    masking: "Yes",
    provisionedToGP: "Yes",
    dateProvisioned: "2025-09-19",
    jira: "DATA-2333",
    credentials: "Vault: feed/comms",
    accessOwners: "Compliance Ops",
    accessType: "Service Account",
    lastChangeDate: "2026-04-25",
    version: "1.5.0",
    comments: "Added SMS channel records.",
  },
];
