-- Seed data for coaction_feed_data_integrations
-- Generated from 'Enterprise Data Inventory.xlsx' sheet 'Data Integrations'

INSERT INTO stage.coaction_feed_data_integrations (domain, source_system, source_platform, integration_interface, target_system, target_layer, target_platform, feed_type, frequency) VALUES
  ('Submission', 'Program Wrapper', 'DB', 'DB extract', 'Submission (DM-EDW)', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Submission', 'Program Wrapper', 'DB', 'DB extract', 'Producer', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Submission', 'Program Wrapper', 'DB', 'DB extract', 'Account', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Submission', 'ClarionDoor (Binding GL Property)', 'Data Lake', 'File drop / lake ingest', 'Submission (DM-EDW)', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Submission', 'ClarionDoor (Binding GL Property)', 'Data Lake', 'File drop / lake ingest', 'Producer', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Submission', 'ClarionDoor (Binding GL Property)', 'Data Lake', 'File drop / lake ingest', 'Account', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Submission', 'SOV (Convr)', 'API / Files', 'API + file ingest', 'Exposure', 'Data Mart', 'Redshift', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'Premiere', 'XML', 'XML feed', 'Exposure', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Policy', 'Premiere', 'XML', 'XML feed', 'Account', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Policy', 'Premiere', 'XML', 'XML feed', 'Submission (DM-EDW)', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'Exposure', 'Data Mart', 'Redshift', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'Reinsurance (Historical)', 'Data Mart', 'Redshift', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'Submission (DM-EDW)', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'Producer', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'Account', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'Exposure', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Rater', 'ICM (Convr)', 'API / Files', 'API + file ingest', 'Exposure', 'Data Mart', 'Redshift', 'Monthly Refresh', 'Monthly'),
  ('Billing', 'Billing (DCOD)', 'DB / SQL Server', 'DB extract', 'Account', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Reinsurance', 'Sapiens (Reinsurance)', 'CSV Files', 'CSV ingest', 'Reinsurance (Historical)', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Third Party', 'DNB (Account)', 'API', 'API ingest', 'Account', 'Data Mart', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Claims', 'TPA Feeds', 'Files', 'File ingest', 'Claim - Count', 'Core EDW', 'Redshift', 'Claims Daily', 'Daily'),
  ('Claims', 'TPA Feeds', 'Files', 'File ingest', 'Premium - Loss', 'Core EDW', 'Redshift', 'Claims Daily', 'Daily'),
  ('Claims', 'Claim Assure (Digitide)', 'Oracle', 'DB extract', 'Claim - Count', 'Core EDW', 'Redshift', 'Claims Daily', 'Daily'),
  ('Claims', 'Claim Assure (Digitide)', 'Oracle', 'DB extract', 'Premium - Loss', 'Core EDW', 'Redshift', 'Claims Daily', 'Daily'),
  ('Claims', 'RDM/CR', 'SQL Server', 'DB extract', 'Premium - Loss', 'Core EDW', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Claims', 'URS Direct', 'Unknown', 'File ingest', 'Premium - Loss', 'Core EDW', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Enterprise', 'Core EDW Models', 'Redshift', 'ETL within EDW', 'Enterprise Reports', 'Core EDW', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Underwriting', 'Core EDW Models', 'Redshift', 'ETL within EDW', 'UWA', 'Core EDW', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Finance', 'CR → Workday (GL)', 'SaaS', 'SaaS integration', 'Premium - Loss', 'Core EDW', 'Redshift', 'Daily Refresh', 'Daily'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'Pricing', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'Actuarial', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'Reserving', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'Loss Analysis', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'CVALIR', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'Billing', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'ProSight EDW', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Policy', 'RDM/CR', 'SQL Server', 'DB extract', 'ProSight Data', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'Pricing', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'Actuarial', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'Reserving', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'Loss Analysis', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'CVALIR', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'Billing', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'ProSight EDW', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Policy', 'BDX', 'Flat Files to SQL Server', 'Batch file ingest', 'ProSight Data', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Rater', 'Coherent Spark', 'API to DB', 'API/DB ingest', 'Pricing', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Rater', 'Coherent Spark', 'API to DB', 'API/DB ingest', 'Actuarial', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Billing', 'Billing (DCOD)', 'DB / SQL Server', 'DB extract', 'Billing', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Rater', 'ICM (Convr)', 'API / Files', 'API + file ingest', 'Loss Analysis', 'EDW Legacy', 'SQL Server', 'Monthly Refresh', 'Monthly'),
  ('Policy', 'ImageRight', 'Files', 'File ingest', 'ProSight Data', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('Claims', 'URS Direct', 'Unknown', 'File ingest', 'ProSight EDW', 'EDW Legacy', 'SQL Server', 'Daily Refresh', 'Daily'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'Verisk', 'External', 'External', 'Daily Refresh', 'Daily'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'P & K', 'External', 'External', 'Monthly Refresh', 'Monthly'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'Paragon', 'External', 'External', 'Monthly Refresh', 'Monthly'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'CSI Watchdog (OFAC)', 'External', 'External', 'Quarterly Refresh', 'Quarterly'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'HSB', 'External', 'External', 'Monthly Refresh', 'Monthly'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'Nexus', 'External', 'External', 'Daily Refresh', 'Daily'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'Premia (LPT)', 'External', 'External', 'Monthly Refresh', 'Monthly'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'Monthly Loss Run', 'External', 'External', 'Monthly Refresh', 'Monthly'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'WC - Unit Stat', 'External', 'External', 'Monthly Refresh', 'Monthly'),
  ('External Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / file / API', 'Reinsurance', 'External', 'External', 'Daily Refresh', 'Daily'),
  ('Internal Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / views', 'Finance (GPPE, GLTE, Earned/Unearned, Gross Loss as of)', 'Internal', 'Internal', 'Daily Refresh', 'Daily'),
  ('Internal Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / views', 'Portals', 'Internal', 'Internal', 'Daily Refresh', 'Daily'),
  ('Internal Distribution', 'EDW / Data Marts', 'Redshift + SQL Server', 'Data extract / views', 'Exposure Extracts (CAT Modeling Team)', 'Internal', 'Internal', 'Daily Refresh', 'Daily'),
  ('Third Party', 'Hazard Hub', 'API', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('Third Party', 'Insurance Services Office (ISO)', 'Files', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('Third Party', 'NCCI', 'Files', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('Third Party', 'American Association of Insurance Services (AAIS)', 'Files', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('Third Party', 'Corelogic', 'API/Files', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('Third Party', 'R.L. Polk', 'Files', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('Third Party', 'Moody''s', 'API', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('HR', 'Activtrak (Attendance Productivity)', 'SaaS', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('HR', 'Egnyte (File Management)', 'Files', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('HR', 'Comp Analyst (Comp Benchmarking Data)', 'Files', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('HR', 'Prevue (Cultural Assessment)', 'SaaS', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('HR', 'Anaplan (Headcount / Budget)', 'SaaS', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('HR', 'Sharepoint (Teams Files)', 'Files', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A'),
  ('HR', 'Sterling (Background Checks)', 'API', 'TBD', 'TBD', 'TBD', 'TBD', 'N/A', 'N/A');

-- Seed data for coaction_feed_api_library
-- Generated from 'Enterprise Data Inventory.xlsx' sheet 'APIs - Extract Data for Portal'

INSERT INTO stage.coaction_feed_api_library (row_num, exportable, row_type, match, name, description, source_owner, source_type, data_source, integration_type, target_owner, target_type, target, status, domain, point_of_contact, origin, questions, notes) VALUES
  (1, 'Yes', 'App to Data Source', 'N', 'Queries EDW for Claims information', 'Queries EDW for Claims information', 'Coaction', 'API', 'Claims API', 'Database Query', 'Coaction', 'Database', 'EDW', 'Active', 'Claims', 'Kip Porterfield', 'Core API Depdendencies', '[Kip Question]: Claims API?', ''),
  (2, 'Yes', 'App to Data Source', 'N', 'Notification Scheduler', 'Provides monthly reporter information from Premiere Billing to the Notification Scheduler.', 'Coaction', 'Job', 'Notification Scheduler', 'Database Query', 'Coaction', 'Database', 'Premiere Billing DB', 'Active', 'Billing', 'Kip Porterfield', 'Core API Depdendencies', '', ''),
  (3, 'Yes', 'App to Data Source', 'N', 'Policy API', 'Retrieves policy status and metadata from Redshift Snapshot', 'Coaction', 'API', 'Policy API', 'Database Query', 'Coaction', 'Database', 'AWS RedShift Snapshot', 'Active', 'Policy', 'Kip Porterfield', 'Core API Depdendencies', '', ''),
  (4, 'Yes', 'App to Data Source', 'N', 'Policy API', 'Policy API retrieves plastic card coverage information from program wrapper', 'Coaction', 'API', 'Policy API', 'Database Query', 'Coaction', 'Database', 'Pricing db', 'Active', 'Policy', 'Kip Porterfield', 'Core API Depdendencies', '', ''),
  (5, 'Yes', 'App to Data Source', 'N', 'Policy API', 'Retrieves policy metadata and financial information from EDW', 'Coaction', 'API', 'Policy API', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Active', 'Policy, Financials', 'Kip Porterfield', 'Core API Depdendencies', '', ''),
  (6, 'Yes', 'App to Data Source', 'N', 'Product API', 'Product API retrieves the claims history for a policy from EDW.

We are not sure why this functionality exists in the Product API. It would be more appropriate in either the Claims API or the Policy API.', 'Coaction', 'API', 'Product API', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Retired?', 'Claims', 'Kip Porterfield', 'Core API Depdendencies', '', ''),
  (7, 'Yes', 'App to Data Source', 'N', 'Display billing data', 'Display billing data', 'Coaction', 'API', 'PSOC/D', 'Database Query', 'Coaction', 'Database', 'Premiere Billing DB', 'Active', 'Billing', 'Deepak Gupta', 'Core API Depdendencies', '', ''),
  (8, 'Yes', 'App to Data Source', 'N', 'Display policy data', 'Display policy data', 'Coaction', 'API', 'PSOC/D', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Active', 'Policy', 'Deepak Gupta', 'Core API Depdendencies', '', ''),
  (9, 'Yes', 'App to Data Source', 'N', 'Display claims data', 'Display claims data', 'Coaction', 'API', 'PSOC/D', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Active', 'Claims', 'Deepak Gupta', 'Core API Depdendencies', '', ''),
  (10, 'Yes', 'App to Data Source', 'N', 'Display account data', 'Display account data', 'Coaction', 'API', 'PSOC/D', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Active', 'Account', 'Deepak Gupta', 'Core API Depdendencies', '', ''),
  (11, 'Yes', 'App to Data Source', 'N', 'Get policy data', 'Get policy data', 'Coaction', 'API', 'Renewal', 'Database Query', 'Coaction', 'Database', 'EDW DB', 'Active', '', 'Kip Porterfield', 'Core API Depdendencies', '', ''),
  (12, 'Yes', 'Source - Transfer - Target', 'N', 'Renewal Service to EDW', 'Pulls expiring policy information to support the renewal process.', 'Coaction', 'API', 'Renewal', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Active', 'Policy', 'Kip Porterfield', 'Core API Depdendencies', '', ''),
  (13, 'Yes', 'Source - Transfer - Target', 'N', 'Renewal Scheduler to EDW', 'Pulls expiring policy information to support the renewal process.', 'Coaction', 'Job', 'Renewal Scheduler', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Active', 'Policy', 'Kip Porterfield', 'Core API Depdendencies', '', ''),
  (14, 'Yes', 'App to Data Source', 'N', 'Display account data', 'Display account data', 'Coaction', 'API', 'PSOP', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Active', 'Account', 'Deepak Gupta', 'Core API Depdendencies', '', ''),
  (15, 'Yes', 'App to Data Source', 'N', 'Display policy data', 'Display policy data', 'Coaction', 'API', 'PSOP', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Active', 'Policy', 'Deepak Gupta', '?', '', ''),
  (16, 'Yes', 'App to Data Source', 'N', 'Display claims data', 'Display claims data', 'Coaction', 'API', 'PSOP', 'Database Query', 'Coaction', 'Database', 'ProSight EDW db', 'Active', 'Claims', 'Deepak Gupta', '?', '', ''),
  (17, 'Yes', 'App to Data Source', 'N', 'Display billing data', 'Display billing data', 'Coaction', 'API', 'PSOP', 'Database Query', 'Coaction', 'Database', 'Premiere Billing DB', 'Active', 'Billing', 'Deepak Gupta', 'Core API Depdendencies', '', '');
