/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddFeedRouteImport } from './routes/add-feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedsFeedIdEditRouteImport } from './routes/feeds.$feedId.edit'

const AddFeedRoute = AddFeedRouteImport.update({
  id: '/add-feed',
  path: '/add-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsFeedIdEditRoute = FeedsFeedIdEditRouteImport.update({
  id: '/feeds/$feedId/edit',
  path: '/feeds/$feedId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-feed': typeof AddFeedRoute
  '/feeds/$feedId/edit': typeof FeedsFeedIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-feed': typeof AddFeedRoute
  '/feeds/$feedId/edit': typeof FeedsFeedIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-feed': typeof AddFeedRoute
  '/feeds/$feedId/edit': typeof FeedsFeedIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-feed' | '/feeds/$feedId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-feed' | '/feeds/$feedId/edit'
  id: '__root__' | '/' | '/add-feed' | '/feeds/$feedId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddFeedRoute: typeof AddFeedRoute
  FeedsFeedIdEditRoute: typeof FeedsFeedIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-feed': {
      id: '/add-feed'
      path: '/add-feed'
      fullPath: '/add-feed'
      preLoaderRoute: typeof AddFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/$feedId/edit': {
      id: '/feeds/$feedId/edit'
      path: '/feeds/$feedId/edit'
      fullPath: '/feeds/$feedId/edit'
      preLoaderRoute: typeof FeedsFeedIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddFeedRoute: AddFeedRoute,
  FeedsFeedIdEditRoute: FeedsFeedIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
